---
# tasks file for my-role
- name: Install nginx 
  ansible.builtin.yum: 
    name: nginx
    state: present
    update_cache: yes
- name: Nginx started & enabled at boot
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
- name: Copy file to path
  ansible.builtin.copy:
    src: files/index.html
    dest: /usr/share/nginx/html/
    owner: root
    group: root
    mode: '0644'

